// Per-race unit rosters — the DEFAULT identity of each race, baked into code
// so the game is asymmetric on its own (Orc ≠ Human) even with no balance.json.
// balance.json (edited in /admin) only layers TUNING on top of these.
// Fields mirror a resolved unit; baseUnits() in ui/balance.js merges them.

export const RACE_UNITS = {
  orcs: {
    grunt: {"name":"Grunt","tier":1,"cost":170,"hp":290,"damage":16,"period":1.04,"range":25,"speed":70,"armor":"light","dmgType":"normal","ranged":false,"projSpeed":420,"splash":0,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg1","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1.5,"projSize":1,"cw":1,"ch":1,"animSpeed":4,"slot":-1,"xp":1},
    slinger: {"name":"Javelin thrower","tier":1,"cost":100,"hp":85,"damage":14,"period":1,"range":180,"speed":70,"armor":"light","dmgType":"normal","ranged":true,"projSpeed":380,"splash":0,"isAir":false,"targetsAir":true,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg1","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1,"projSize":1.35,"cw":1,"ch":1,"animSpeed":5,"slot":-1,"xp":1},
    crab: {"name":"Boar rider","tier":2,"cost":115,"hp":135,"damage":35,"period":1.1,"range":5,"speed":70,"armor":"light","dmgType":"normal","ranged":false,"projSpeed":300,"splash":0,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg3","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1.25,"projSize":1,"cw":2,"ch":1,"animSpeed":4,"slot":-1,"xp":1},
    bruiser: {"name":"Shaman","tier":2,"cost":150,"hp":155,"damage":13,"period":1.37,"range":80,"speed":70,"armor":"light","dmgType":"normal","ranged":true,"projSpeed":275,"splash":0,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg2","food":1,"caster":true,"autoAttackBetween":true,"abilities":["hasteaura","regenaura"],"mana":200,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1.1,"projSize":0.9,"cw":1,"ch":1,"animSpeed":3.5,"slot":-1,"xp":1},
    lancer: {"name":"Wyvern rider","tier":3,"cost":300,"hp":215,"damage":19,"period":1.2,"range":220,"speed":70,"armor":"light","dmgType":"normal","ranged":true,"projSpeed":380,"splash":0,"isAir":true,"targetsAir":true,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg3","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":3,"projSize":1,"cw":2,"ch":2,"animSpeed":1.5,"slot":-1,"xp":1},
    dasher: {"name":"Totemic Shaman","tier":1,"cost":120,"hp":110,"damage":6,"period":1.1,"range":130,"speed":70,"armor":"light","dmgType":"normal","ranged":true,"projSpeed":320,"splash":0,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg2","food":1,"caster":true,"autoAttackBetween":false,"abilities":["empower","slowingtotem"],"mana":200,"manaRegen":3,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1.45,"projSize":0.7,"cw":1,"ch":1,"animSpeed":4,"slot":-1,"xp":1},
    wasp: {"name":"Two headed ogre","tier":2,"cost":125,"hp":175,"damage":18,"period":0.8,"range":80,"speed":70,"armor":"armored","dmgType":"normal","ranged":false,"projSpeed":420,"splash":0,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg3","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":2.5,"projSize":1,"cw":1,"ch":2,"animSpeed":2.5,"slot":-1,"xp":1},
    archon: {"name":"Stonehide Basilisk","tier":3,"cost":310,"hp":640,"damage":40,"period":1.5,"range":90,"speed":70,"armor":"armored","dmgType":"normal","ranged":false,"projSpeed":420,"splash":90,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":45,"building":"bldg3","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":3,"projSize":1,"cw":2,"ch":2,"animSpeed":1.7,"slot":-1,"xp":1},
    mender: {"name":"Orc catapult","tier":2,"cost":100,"hp":80,"damage":13,"period":2.2,"range":210,"speed":70,"armor":"light","dmgType":"normal","ranged":true,"projSpeed":320,"splash":70,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg1","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1.85,"projSize":0.5,"cw":2,"ch":1,"animSpeed":2.5,"slot":-1,"xp":1},
  },
  humans: {
    grunt: {"name":"Footman","tier":1,"cost":110,"hp":220,"damage":12,"period":0.88,"range":25,"speed":70,"armor":"light","dmgType":"normal","ranged":false,"projSpeed":420,"splash":0,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg1","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1,"projSize":1,"cw":1,"ch":1,"animSpeed":4,"slot":-1,"xp":1},
    slinger: {"name":"Archer","tier":1,"cost":155,"hp":150,"damage":22,"period":1.17,"range":200,"speed":70,"armor":"light","dmgType":"normal","ranged":true,"projSpeed":420,"splash":0,"isAir":false,"targetsAir":true,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg1","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1.1,"projSize":0.7,"cw":1,"ch":1,"animSpeed":4,"slot":-1,"xp":1},
    crab: {"name":"Giant Eagle","tier":1,"cost":105,"hp":80,"damage":10,"period":0.8,"range":20,"speed":70,"armor":"light","dmgType":"normal","ranged":false,"projSpeed":300,"splash":0,"isAir":true,"targetsAir":true,"targetsGround":false,"heal":false,"buildingDamage":0,"building":"bldg2","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":true,"dashDamage":35,"dashSpeed":400,"dashRange":250,"dashCd":12,"size":1,"projSize":1,"cw":1,"ch":1,"animSpeed":2.5,"slot":-1,"xp":1},
    bruiser: {"name":"Priest","tier":2,"cost":160,"hp":100,"damage":12,"period":1.3,"range":160,"speed":70,"armor":"light","dmgType":"normal","ranged":true,"projSpeed":420,"splash":0,"isAir":false,"targetsAir":true,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg3","food":1,"caster":true,"autoAttackBetween":true,"abilities":["heal","frostbolt"],"mana":200,"manaRegen":0.72,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":0.6,"projSize":1,"cw":1,"ch":1,"animSpeed":4,"slot":-1,"xp":1},
    lancer: {"name":"Huntress","tier":2,"cost":175,"hp":200,"damage":18,"period":1.17,"range":160,"speed":70,"armor":"light","dmgType":"piercing","ranged":true,"projSpeed":420,"splash":0,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg2","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":true,"bouncePower":40,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1.75,"projSize":1,"cw":2,"ch":1,"animSpeed":3,"slot":-1,"xp":1},
    dasher: {"name":"Siege Cannon","tier":2,"cost":110,"hp":95,"damage":19,"period":2.2,"range":250,"speed":70,"armor":"light","dmgType":"normal","ranged":true,"projSpeed":420,"splash":40,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":55,"building":"bldg1","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":2.2,"projSize":0.5,"cw":2,"ch":1,"animSpeed":1.4,"slot":-1,"xp":1},
    wasp: {"name":"Royal Knight","tier":3,"cost":325,"hp":480,"damage":22,"period":0.8,"range":75,"speed":70,"armor":"armored","dmgType":"normal","ranged":false,"projSpeed":420,"splash":0,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg1","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":2.85,"projSize":1,"cw":2,"ch":2,"animSpeed":2.5,"slot":-1,"xp":1},
    archon: {"name":"Lightblade Weaver","tier":3,"cost":125,"hp":150,"damage":24,"period":1,"range":45,"speed":70,"armor":"light","dmgType":"piercing","ranged":false,"projSpeed":420,"splash":0,"isAir":false,"targetsAir":true,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg3","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1.2,"projSize":1,"cw":1,"ch":1,"animSpeed":3.5,"slot":-1,"xp":1},
    mender: {"name":"Griffin rider","tier":3,"cost":350,"hp":190,"damage":23,"period":1.75,"range":170,"speed":70,"armor":"armored","dmgType":"normal","ranged":true,"projSpeed":280,"splash":0,"isAir":true,"targetsAir":true,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg2","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":2.7,"projSize":0.8,"cw":2,"ch":2,"animSpeed":1.5,"slot":-1,"xp":1},
  },
  undead: {
    grunt: {"name":"1","tip":"Melee ieftin, rapid","tipEn":"Cheap, fast melee","tier":1,"cost":110,"hp":200,"damage":15,"period":0.85,"range":25,"speed":70,"armor":"light","dmgType":"normal","ranged":false,"projSpeed":420,"splash":0,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg1","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1,"projSize":1,"cw":1,"ch":1,"animSpeed":4.5,"slot":-1,"xp":1},
    slinger: {"name":"2","tip":"Necromancer: ridică schelete din cadavre (Melee / Ranged / Brothers Skeleton — deblocate cu upgrade). Nucleul economiei Undead.","tipEn":"Necromancer: raises skeletons from corpses (Melee / Ranged / Brothers Skeleton — unlocked by upgrades). The core of the Undead economy.","tier":1,"cost":140,"hp":110,"damage":10,"period":1.3,"range":150,"speed":70,"armor":"light","dmgType":"normal","ranged":true,"projSpeed":360,"splash":0,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg1","food":1,"caster":true,"autoAttackBetween":true,"abilities":["skeletonmelee","skeletonranged","skeletonbrothers"],"mana":200,"manaRegen":3,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1,"projSize":0.9,"cw":1,"ch":1,"animSpeed":3.5,"slot":-1,"xp":1},
    dasher: {"name":"3","tip":"Groapar: sapă cadavre din pământ când inamicii se apropie. Nu atacă.","tipEn":"Grave Digger: digs corpses out of the ground when enemies come near. Does not attack.","tier":1,"cost":90,"hp":90,"damage":0,"period":1,"range":0,"speed":70,"armor":"light","dmgType":"normal","ranged":false,"projSpeed":420,"splash":0,"isAir":false,"targetsAir":false,"targetsGround":false,"heal":false,"buildingDamage":0,"building":"bldg2","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1,"projSize":1,"cw":1,"ch":1,"animSpeed":3,"slot":-1,"xp":1,"gravedig":true,"digRange":260,"digInterval":4,"hopRadius":70,"digBig":false,"fleeRange":140,"fleeSpeed":140},
    crab: {"name":"4","tip":"Ranged, anti-air","tipEn":"Ranged, anti-air","tier":2,"cost":140,"hp":170,"damage":20,"period":1.2,"range":180,"speed":70,"armor":"light","dmgType":"piercing","ranged":true,"projSpeed":380,"splash":0,"isAir":false,"targetsAir":true,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg3","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1.4,"projSize":1,"cw":2,"ch":1,"animSpeed":3,"slot":-1,"xp":1},
    bruiser: {"name":"5","tip":"(placeholder — de definit)","tipEn":"(placeholder — to be defined)","tier":2,"cost":160,"hp":180,"damage":18,"period":1.1,"range":30,"speed":70,"armor":"armored","dmgType":"normal","ranged":false,"projSpeed":420,"splash":0,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg2","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1.2,"projSize":0.9,"cw":1,"ch":1,"animSpeed":3,"slot":-1,"xp":1},
    lancer: {"name":"6","tip":"Aerian greu","tipEn":"Heavy flyer","tier":3,"cost":300,"hp":250,"damage":26,"period":1.3,"range":220,"speed":70,"armor":"light","dmgType":"normal","ranged":true,"projSpeed":380,"splash":0,"isAir":true,"targetsAir":true,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg3","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":3,"projSize":1,"cw":2,"ch":2,"animSpeed":1.5,"slot":-1,"xp":1},
    wasp: {"name":"7","tip":"Liliac-tanc zburător: în aer atacă doar zburătorii, de aproape (fără proiectil) — interceptor anti-air. Abilitatea Aterizare îl coboară ca tanc melee terestru care blochează lane-ul.","tipEn":"Flying tank bat: in the air it hits only flyers, up close (no projectile) — an anti-air interceptor. The Landing ability drops it down as a ground melee tank that plugs the lane.","tier":3,"cost":300,"hp":470,"damage":20,"period":1.2,"range":90,"speed":70,"armor":"armored","dmgType":"normal","ranged":false,"projSpeed":420,"splash":0,"isAir":true,"targetsAir":true,"targetsGround":false,"heal":false,"buildingDamage":0,"building":"bldg3","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"landArmor":"armored","mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":2.6,"projSize":1,"cw":1,"ch":2,"animSpeed":2.2,"slot":-1,"xp":1},
    archon: {"name":"8","tip":"Melee cu splash","tipEn":"Melee with splash","tier":3,"cost":315,"hp":620,"damage":40,"period":1.5,"range":60,"speed":70,"armor":"armored","dmgType":"normal","ranged":false,"projSpeed":420,"splash":90,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":45,"building":"bldg3","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":3,"projSize":1,"cw":2,"ch":2,"animSpeed":1.7,"slot":-1,"xp":1},
    mender: {"name":"9","tip":"Artilerie","tipEn":"Artillery","tier":2,"cost":100,"hp":90,"damage":14,"period":2.2,"range":210,"speed":70,"armor":"light","dmgType":"normal","ranged":true,"projSpeed":320,"splash":70,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg1","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1.9,"projSize":0.5,"cw":2,"ch":1,"animSpeed":2.5,"slot":-1,"xp":1},
  },
  // Wood Elves: fragile, long-ranged and fast-hitting. Their tanks are not
  // armoured soldiers but woken trees, and their beasts follow along rather
  // than being ridden. bldg1 = the hunting line, bldg2 = the grove (casters +
  // treant), bldg3 = the old things of the forest.
  woodelves: {
    grunt: {"name":"Glade Warden","tip":"Nu apără un hotar, ci un luminiș anume, pe care îl știe de o sută de ani. Cel mai iute braț de tier 1 din joc.","tipEn":"It guards no border — only one particular glade, known for a hundred years. The quickest arm at tier one.","tier":1,"cost":105,"hp":175,"damage":15,"period":0.82,"range":25,"speed":70,"armor":"light","dmgType":"normal","ranged":false,"projSpeed":420,"splash":0,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg1","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1,"projSize":1,"cw":1,"ch":1,"animSpeed":4.5,"slot":-1,"xp":1},
    slinger: {"name":"Longbow Archer","tip":"Trage de la o distanță la care ținta încă nu știe că e țintă. Cea mai lungă rază din tot jocul, și ajunge și la ce zboară.","tipEn":"It looses from a distance at which the target does not yet know it is one. The longest range in the game, and it reaches what flies.","tier":1,"cost":150,"hp":105,"damage":21,"period":1.1,"range":230,"speed":70,"armor":"light","dmgType":"normal","ranged":true,"projSpeed":460,"splash":0,"isAir":false,"targetsAir":true,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg1","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1.05,"projSize":0.7,"cw":1,"ch":1,"animSpeed":4,"slot":-1,"xp":1},
    crab: {"name":"Forest Wolf","tip":"Nu e îmblânzit și nu are stăpân; merge în aceeași direcție fiindcă vrea aceleași lucruri. Se aruncă din fugă peste ce prinde descoperit.","tipEn":"It is not tamed and has no master; it runs the same way because it wants the same things. It leaps from a run onto whatever it catches in the open.","tier":2,"cost":120,"hp":145,"damage":24,"period":0.9,"range":20,"speed":70,"armor":"light","dmgType":"normal","ranged":false,"projSpeed":420,"splash":0,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg3","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":true,"dashDamage":28,"dashSpeed":480,"dashRange":230,"dashCd":10,"size":1.3,"projSize":1,"cw":2,"ch":1,"animSpeed":5,"slot":-1,"xp":1},
    bruiser: {"name":"Treant","tip":"Nu a fost chemat — s-a trezit fiindcă cineva a pus toporul unde nu trebuia. Se mișcă rar și lovește rar, dar între el și restul armatei nu trece nimic.","tipEn":"It was not summoned — it woke because someone set an axe where they should not have. It moves seldom and strikes seldom, but nothing gets past it to the rest of the army.","tier":2,"cost":210,"hp":430,"damage":24,"period":1.45,"range":40,"speed":70,"armor":"armored","dmgType":"normal","ranged":false,"projSpeed":420,"splash":0,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg2","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":2.4,"projSize":1,"cw":2,"ch":2,"animSpeed":2,"slot":-1,"xp":1},
    lancer: {"name":"Glaive Thrower","tip":"Lama pleacă, lovește de trei ori și se întoarce în mână fără să fie chemată. Făcută pentru cei care merg îngrămădiți.","tipEn":"The blade leaves, strikes three times and returns to the hand unbidden. Made for those who march bunched together.","tier":2,"cost":180,"hp":190,"damage":19,"period":1.15,"range":165,"speed":70,"armor":"light","dmgType":"piercing","ranged":true,"projSpeed":430,"splash":0,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg1","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":true,"bouncePower":45,"bounceRadius":85,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1.7,"projSize":1,"cw":2,"ch":1,"animSpeed":3,"slot":-1,"xp":1},
    dasher: {"name":"Dryad","tip":"Se desprinde dintr-un copac și nu se îndepărtează niciodată prea mult de el. Încetinește tot ce se apropie și închide rănile celor din jur, între două săgeți.","tipEn":"It steps out of a tree and never strays far from it. It slows all that draw near and closes the wounds of those around it, between two arrows.","tier":1,"cost":130,"hp":100,"damage":9,"period":1.1,"range":145,"speed":70,"armor":"light","dmgType":"normal","ranged":true,"projSpeed":380,"splash":0,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg2","food":1,"caster":true,"autoAttackBetween":true,"abilities":["slowaura","regenaura"],"mana":200,"manaRegen":3,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1,"projSize":0.8,"cw":1,"ch":1,"animSpeed":3.5,"slot":-1,"xp":1},
    wasp: {"name":"Great Owl","tip":"Trece pe deasupra fără niciun zgomot, ceea ce e cel mai rău lucru pe care îl poate face o pasăre de mărimea asta. Lovește și la sol și în aer, de sus.","tipEn":"It passes overhead without a sound, which is the worst thing a bird that size can do. It strikes both ground and air, from above.","tier":3,"cost":290,"hp":205,"damage":24,"period":1.25,"range":210,"speed":70,"armor":"light","dmgType":"normal","ranged":true,"projSpeed":400,"splash":0,"isAir":true,"targetsAir":true,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg3","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":2.6,"projSize":0.9,"cw":2,"ch":2,"animSpeed":2,"slot":-1,"xp":1},
    archon: {"name":"Ancient Protector","tip":"Cel mai bătrân lucru din pădure și singurul pe care pădurea îl trezește ea însăși. Fiecare lovitură prinde tot ce stă lângă țintă, iar zidurile cedează sub el.","tipEn":"The oldest thing in the forest, and the only one the forest wakes by itself. Every blow catches whatever stands near the target, and walls give under it.","tier":3,"cost":320,"hp":610,"damage":42,"period":1.6,"range":85,"speed":70,"armor":"armored","dmgType":"normal","ranged":false,"projSpeed":420,"splash":85,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":50,"building":"bldg3","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":3,"projSize":1,"cw":2,"ch":2,"animSpeed":1.6,"slot":-1,"xp":1},
    mender: {"name":"Grove Keeper","tip":"Nu cere pădurii nimic; îi dă înapoi. Vindecă aliatul cel mai rănit din apropiere și lovește și ce zboară.","tipEn":"It asks the forest for nothing; it gives back. It heals the most wounded ally nearby and strikes what flies as well.","tier":2,"cost":155,"hp":115,"damage":12,"period":1.25,"range":155,"speed":70,"armor":"light","dmgType":"normal","ranged":true,"projSpeed":400,"splash":0,"isAir":false,"targetsAir":true,"targetsGround":true,"heal":true,"buildingDamage":0,"building":"bldg2","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":0.9,"projSize":0.8,"cw":1,"ch":1,"animSpeed":4,"slot":-1,"xp":1},
  },
};
