// Per-race unit rosters — the DEFAULT identity of each race, baked into code
// so the game is asymmetric on its own (Orc ≠ Human) even with no balance.json.
// balance.json (edited in /admin) only layers TUNING on top of these.
// Fields mirror a resolved unit; baseUnits() in ui/balance.js merges them.

export const RACE_UNITS = {
  orcs: {
    grunt: {"name":"Grunt","tier":1,"cost":170,"hp":290,"damage":16,"period":1.04,"range":25,"speed":70,"armor":"light","dmgType":"normal","ranged":false,"projSpeed":420,"splash":0,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg1","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1.5,"projSize":1,"cw":1,"ch":1,"animSpeed":4,"slot":-1,"xp":1},
    slinger: {"name":"Javelin thrower","tier":1,"cost":100,"hp":85,"damage":14,"period":1,"range":180,"speed":70,"armor":"light","dmgType":"normal","ranged":true,"projSpeed":380,"splash":0,"isAir":false,"targetsAir":true,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg1","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1,"projSize":1.35,"cw":1,"ch":1,"animSpeed":5,"slot":-1,"xp":1},
    crab: {"name":"Boar rider","tier":2,"cost":115,"hp":135,"damage":35,"period":1.1,"range":5,"speed":70,"armor":"light","dmgType":"normal","ranged":false,"projSpeed":300,"splash":0,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg3","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1.25,"projSize":1,"cw":2,"ch":1,"animSpeed":4,"slot":-1,"xp":1},
    bruiser: {"name":"Shaman","tier":2,"cost":150,"hp":155,"damage":13,"period":1.37,"range":80,"speed":70,"armor":"light","dmgType":"normal","ranged":true,"projSpeed":275,"splash":0,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg2","food":1,"caster":true,"autoAttackBetween":true,"abilities":["hasteaura","regenaura"],"mana":200,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1.1,"projSize":0.9,"cw":1,"ch":1,"animSpeed":3.5,"slot":-1,"xp":1},
    lancer: {"name":"Wyvern rider","tier":3,"cost":300,"hp":215,"damage":19,"period":1.2,"range":220,"speed":70,"armor":"light","dmgType":"normal","ranged":true,"projSpeed":380,"splash":0,"isAir":true,"targetsAir":true,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg3","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":3,"projSize":1,"cw":2,"ch":2,"animSpeed":1.5,"slot":-1,"xp":1},
    dasher: {"name":"Totemic Shaman","tier":1,"cost":120,"hp":110,"damage":6,"period":1.1,"range":130,"speed":70,"armor":"light","dmgType":"normal","ranged":true,"projSpeed":320,"splash":0,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg2","food":1,"caster":true,"autoAttackBetween":false,"abilities":["empower","slowingtotem"],"mana":200,"manaRegen":3,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1.45,"projSize":0.7,"cw":1,"ch":1,"animSpeed":4,"slot":-1,"xp":1},
    wasp: {"name":"Two headed ogre","tier":2,"cost":125,"hp":175,"damage":18,"period":0.8,"range":80,"speed":70,"armor":"armored","dmgType":"normal","ranged":false,"projSpeed":420,"splash":0,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg3","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":2.5,"projSize":1,"cw":1,"ch":2,"animSpeed":2.5,"slot":-1,"xp":1},
    archon: {"name":"Stonehide Basilisk","tier":3,"cost":310,"hp":640,"damage":40,"period":1.5,"range":90,"speed":70,"armor":"armored","dmgType":"normal","ranged":false,"projSpeed":420,"splash":90,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":45,"building":"bldg3","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":3,"projSize":1,"cw":2,"ch":2,"animSpeed":1.7,"slot":-1,"xp":1},
    mender: {"name":"Orc catapult","tier":2,"cost":100,"hp":80,"damage":13,"period":2.2,"range":210,"speed":70,"armor":"light","dmgType":"normal","ranged":true,"projSpeed":320,"splash":70,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg1","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1.85,"projSize":0.5,"cw":2,"ch":1,"animSpeed":2.5,"slot":-1,"xp":1},
  },
  humans: {
    grunt: {"name":"Footman","tier":1,"cost":110,"hp":220,"damage":12,"period":0.88,"range":25,"speed":70,"armor":"light","dmgType":"normal","ranged":false,"projSpeed":420,"splash":0,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg1","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1,"projSize":1,"cw":1,"ch":1,"animSpeed":4,"slot":-1,"xp":1},
    slinger: {"name":"Archer","tier":1,"cost":155,"hp":150,"damage":22,"period":1.17,"range":200,"speed":70,"armor":"light","dmgType":"normal","ranged":true,"projSpeed":420,"splash":0,"isAir":false,"targetsAir":true,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg1","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1.1,"projSize":0.7,"cw":1,"ch":1,"animSpeed":4,"slot":-1,"xp":1},
    crab: {"name":"Giant Eagle","tier":1,"cost":105,"hp":80,"damage":10,"period":0.8,"range":20,"speed":70,"armor":"light","dmgType":"normal","ranged":false,"projSpeed":300,"splash":0,"isAir":true,"targetsAir":true,"targetsGround":false,"heal":false,"buildingDamage":0,"building":"bldg2","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":true,"dashDamage":35,"dashSpeed":400,"dashRange":250,"dashCd":12,"size":1,"projSize":1,"cw":1,"ch":1,"animSpeed":2.5,"slot":-1,"xp":1},
    bruiser: {"name":"Priest","tier":2,"cost":160,"hp":100,"damage":12,"period":1.3,"range":160,"speed":70,"armor":"light","dmgType":"normal","ranged":true,"projSpeed":420,"splash":0,"isAir":false,"targetsAir":true,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg3","food":1,"caster":true,"autoAttackBetween":true,"abilities":["heal","frostbolt"],"mana":200,"manaRegen":0.72,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":0.6,"projSize":1,"cw":1,"ch":1,"animSpeed":4,"slot":-1,"xp":1},
    lancer: {"name":"Huntress","tier":2,"cost":175,"hp":200,"damage":18,"period":1.17,"range":160,"speed":70,"armor":"light","dmgType":"piercing","ranged":true,"projSpeed":420,"splash":0,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg2","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":true,"bouncePower":40,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1.75,"projSize":1,"cw":2,"ch":1,"animSpeed":3,"slot":-1,"xp":1},
    dasher: {"name":"Siege Cannon","tier":2,"cost":110,"hp":95,"damage":19,"period":2.2,"range":250,"speed":70,"armor":"light","dmgType":"normal","ranged":true,"projSpeed":420,"splash":40,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":55,"building":"bldg1","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":2.2,"projSize":0.5,"cw":2,"ch":1,"animSpeed":1.4,"slot":-1,"xp":1},
    wasp: {"name":"Royal Knight","tier":3,"cost":325,"hp":480,"damage":22,"period":0.8,"range":75,"speed":70,"armor":"armored","dmgType":"normal","ranged":false,"projSpeed":420,"splash":0,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg1","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":2.85,"projSize":1,"cw":2,"ch":2,"animSpeed":2.5,"slot":-1,"xp":1},
    archon: {"name":"Lightblade Weaver","tier":3,"cost":125,"hp":150,"damage":24,"period":1,"range":45,"speed":70,"armor":"light","dmgType":"piercing","ranged":false,"projSpeed":420,"splash":0,"isAir":false,"targetsAir":true,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg3","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1.2,"projSize":1,"cw":1,"ch":1,"animSpeed":3.5,"slot":-1,"xp":1},
    mender: {"name":"Griffin rider","tier":3,"cost":350,"hp":190,"damage":23,"period":1.75,"range":170,"speed":70,"armor":"armored","dmgType":"normal","ranged":true,"projSpeed":280,"splash":0,"isAir":true,"targetsAir":true,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg2","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":2.7,"projSize":0.8,"cw":2,"ch":2,"animSpeed":1.5,"slot":-1,"xp":1},
  },
  undead: {
    grunt: {"name":"1","tip":"Melee ieftin, rapid","tier":1,"cost":110,"hp":200,"damage":15,"period":0.85,"range":25,"speed":70,"armor":"light","dmgType":"normal","ranged":false,"projSpeed":420,"splash":0,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg1","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1,"projSize":1,"cw":1,"ch":1,"animSpeed":4.5,"slot":-1,"xp":1},
    slinger: {"name":"2","tip":"Necromancer: ridică schelete din cadavre (Melee / Ranged / Brothers Skeleton — deblocate cu upgrade). Nucleul economiei Undead.","tier":1,"cost":140,"hp":110,"damage":10,"period":1.3,"range":150,"speed":70,"armor":"light","dmgType":"normal","ranged":true,"projSpeed":360,"splash":0,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg1","food":1,"caster":true,"autoAttackBetween":true,"abilities":["skeletonmelee","skeletonranged","skeletonbrothers"],"mana":200,"manaRegen":3,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1,"projSize":0.9,"cw":1,"ch":1,"animSpeed":3.5,"slot":-1,"xp":1},
    dasher: {"name":"3","tip":"Groapar: sapă cadavre din pământ când inamicii se apropie. Nu atacă.","tier":1,"cost":90,"hp":90,"damage":0,"period":1,"range":0,"speed":70,"armor":"light","dmgType":"normal","ranged":false,"projSpeed":420,"splash":0,"isAir":false,"targetsAir":false,"targetsGround":false,"heal":false,"buildingDamage":0,"building":"bldg2","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1,"projSize":1,"cw":1,"ch":1,"animSpeed":3,"slot":-1,"xp":1,"gravedig":true,"digRange":260,"digInterval":4,"hopRadius":70,"digBig":false,"fleeRange":140,"fleeSpeed":140},
    crab: {"name":"4","tip":"Ranged, anti-air","tier":2,"cost":140,"hp":170,"damage":20,"period":1.2,"range":180,"speed":70,"armor":"light","dmgType":"piercing","ranged":true,"projSpeed":380,"splash":0,"isAir":false,"targetsAir":true,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg3","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1.4,"projSize":1,"cw":2,"ch":1,"animSpeed":3,"slot":-1,"xp":1},
    bruiser: {"name":"5","tip":"(placeholder — de definit)","tier":2,"cost":160,"hp":180,"damage":18,"period":1.1,"range":30,"speed":70,"armor":"armored","dmgType":"normal","ranged":false,"projSpeed":420,"splash":0,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg2","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1.2,"projSize":0.9,"cw":1,"ch":1,"animSpeed":3,"slot":-1,"xp":1},
    lancer: {"name":"6","tip":"Aerian greu","tier":3,"cost":300,"hp":250,"damage":26,"period":1.3,"range":220,"speed":70,"armor":"light","dmgType":"normal","ranged":true,"projSpeed":380,"splash":0,"isAir":true,"targetsAir":true,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg3","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":3,"projSize":1,"cw":2,"ch":2,"animSpeed":1.5,"slot":-1,"xp":1},
    wasp: {"name":"7","tip":"Liliac-tanc zburător: în aer atacă doar zburătorii, de aproape (fără proiectil) — interceptor anti-air. Abilitatea Aterizare îl coboară ca tanc melee terestru care blochează lane-ul.","tier":3,"cost":300,"hp":470,"damage":20,"period":1.2,"range":90,"speed":70,"armor":"armored","dmgType":"normal","ranged":false,"projSpeed":420,"splash":0,"isAir":true,"targetsAir":true,"targetsGround":false,"heal":false,"buildingDamage":0,"building":"bldg3","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"landArmor":"armored","mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":2.6,"projSize":1,"cw":1,"ch":2,"animSpeed":2.2,"slot":-1,"xp":1},
    archon: {"name":"8","tip":"Melee cu splash","tier":3,"cost":315,"hp":620,"damage":40,"period":1.5,"range":60,"speed":70,"armor":"armored","dmgType":"normal","ranged":false,"projSpeed":420,"splash":90,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":45,"building":"bldg3","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":3,"projSize":1,"cw":2,"ch":2,"animSpeed":1.7,"slot":-1,"xp":1},
    mender: {"name":"9","tip":"Artilerie","tier":2,"cost":100,"hp":90,"damage":14,"period":2.2,"range":210,"speed":70,"armor":"light","dmgType":"normal","ranged":true,"projSpeed":320,"splash":70,"isAir":false,"targetsAir":false,"targetsGround":true,"heal":false,"buildingDamage":0,"building":"bldg1","food":1,"caster":false,"autoAttackBetween":false,"abilities":[],"mana":100,"manaRegen":2,"bounce":false,"bouncePower":50,"bounceRadius":80,"bounceMax":3,"dash":false,"dashDamage":30,"dashSpeed":400,"dashRange":250,"dashCd":3,"size":1.9,"projSize":0.5,"cw":2,"ch":1,"animSpeed":2.5,"slot":-1,"xp":1},
  },
};
